# gcloud container builds submit --config cloudbuild.yaml --substitutions=_PATH=.,_VERSION=dev-20180612 .

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--tag', 'us.gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${COMMIT_SHA}${_VERSION}', '${_PATH}' ]

substitutions:
  _PATH: pipeline
  _IMAGE_NAME: blast-pipeline
  _VERSION:

images:
  - 'us.gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${COMMIT_SHA}${_VERSION}'
